## Sign_UP
POST http://localhost:8181/sso/sign_up
content-type: application/json

{
  "ua": "t1",
  "ip": "124.1.2.3",
  "email": "t1@mail.com",
  "password": "tesTPass114*",
  "phone": "+9999999999"
}

###

## Sign_IN
POST http://localhost:8181/sso/sign_in
content-type: application/json

{
  "email": "t1@mail.com",
  "ua": "t1",
  "ip": "124.1.2.3",
  "password": "testTPass1331*"
}

###
## Change Password
POST http://localhost:8181/sso/my/change/password
content-type: application/json
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMjoxMzo1MS4yNjYwOTk1WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.GXg7Q9J0bUiH6hJbhFlUQVIxMuXJAzdrahsSfcqHvFQ

{
  "new_password": "NEwtestTPass411*",
  "old_password": "testTPass411*"
}

###

## LogOut
POST http://localhost:8181/sso/my/logout
UA: t1
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMjoxMzo1MS4yNjYwOTk1WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.GXg7Q9J0bUiH6hJbhFlUQVIxMuXJAzdrahsSfcqHvFQ



###
POST http://localhost:8181/sso/my/change/phone
content-type: application/json

{
  "email": "testsignin@mail.com",
  "phone": "testNumberTwo"
}