## Sign_UP
POST http://localhost:8181/sso/sign_up
content-type: application/json

{
  "ua": "t2",
  "ip": "124.1.2.3",
  "email": "t2@mail.com",
  "password": "tesTPass114*",
  "phone": "+9999999999"
}

###

## Sign_IN
POST http://localhost:8181/sso/sign_in
content-type: application/json

{
  "email": "t1@mail.com",
  "ua": "t1",
  "ip": "testIp",
  "password": "tesTPass114*"
}

###

## LogOut
POST http://localhost:8181/sso/my/logout
UA: t2
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQyQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMVQyMDoxMDozNi43NTIyMjU5WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiNmIxZGY2NjMtM2E0OS00YzQxLWI1OWEtN2JhOGExZjcwMjNjIn0.MYRJT3DZgvxp8B2rQ9Z10-3F4krvqS3Qvih_LnOhfp4



###
POST http://localhost:8181/sso/my/change/phone
content-type: application/json

{
  "email": "testsignin@mail.com",
  "phone": "testNumberTwo"
}